security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        doctrine:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        # test:
        #     http_basic: ~
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern: ^/
            form_login:
                login_path: login
                check_path: login
                always_use_default_target_path:  true
                default_target_path:  /
            remember_me:
                secret:      "%kernel.secret%"
                # possible values: 'strict', 'lax' and null
                samesite: null
            logout:
                path:   /logout
                target: /home

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/signup, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
